apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for timescale.hyperplane.hu/v1alpha1, Kind: TimescaledbMultinode
##
- apiGroups:
  - timescale.hyperplane.hu
  resources:
  - timescaledbmultinodes
  - timescaledbmultinodes/status
  - timescaledbmultinodes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "secrets"
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "jobs"

#+kubebuilder:scaffold:rules
