# permissions for end users to edit timescaledbmultinodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: timescaledbmultinode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: timescale-operator
    app.kubernetes.io/part-of: timescale-operator
    app.kubernetes.io/managed-by: kustomize
  name: timescaledbmultinode-editor-role
rules:
- apiGroups:
  - timescale.hyperplane.hu
  resources:
  - timescaledbmultinodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - timescale.hyperplane.hu
  resources:
  - timescaledbmultinodes/status
  verbs:
  - get
