apiVersion: timescale.hyperplane.hu/v1alpha1
kind: TimescaledbMultinode
metadata:
  name: timescaledbmultinode-sample
spec:
  # Default values copied from <project_dir>/helm-charts/timescaledb-multinode/values.yaml
  affinity: {}
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app:  {{ template "timescaledb.name" . }}
              release: {{ .Release.Name | quote }}
  credentials:
    accessNode:
      superuser: tea
    dataNode:
      superuser: coffee
  dataNodes: 3
  env:
  - name: LC_ALL
    value: C.UTF-8
  - name: LANG
    value: C.UTF-8
  - name: PGDATA
    value: /var/lib/postgresql/pgdata
  image:
    pullPolicy: IfNotPresent
    repository: timescaledev/timescaledb-ha
    tag: pg12-ts2.0.0-p0
  nameOverride: timescaledb
  nodeSelector: {}
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    annotations: {}
    enabled: true
    mountPath: /var/lib/postgresql
    size: 5G
    subPath: ""
  postgresql:
    databases:
    - postgres
    - example
    parameters:
      log_checkpoints: "on"
      log_connections: "on"
      log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
      log_lock_waits: "on"
      log_min_duration_statement: 1s
      log_statement: ddl
      max_connections: 100
      max_prepared_transactions: 150
      max_wal_size: 512MB
      min_wal_size: 256MB
      shared_buffers: 300MB
      temp_file_limit: 1GB
      timescaledb.passfile: ../.pgpass
      work_mem: 16MB
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
  tolerations: []
  
  
